package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.Company;
import pojo.CompanyExample;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company
     *
     * @mbg.generated Wed Jun 26 11:13:44 CST 2019
     */
    long countByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company
     *
     * @mbg.generated Wed Jun 26 11:13:44 CST 2019
     */
    int deleteByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company
     *
     * @mbg.generated Wed Jun 26 11:13:44 CST 2019
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company
     *
     * @mbg.generated Wed Jun 26 11:13:44 CST 2019
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company
     *
     * @mbg.generated Wed Jun 26 11:13:44 CST 2019
     */
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company
     *
     * @mbg.generated Wed Jun 26 11:13:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_company
     *
     * @mbg.generated Wed Jun 26 11:13:44 CST 2019
     */
    int updateByExample(@Param("record") Company record, @Param("example") CompanyExample example);
}